### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ricleal** [NGuernse/plotfit-vuetify#1]
- [x] Fetch Data needs some information saying the fetch was successful
- [x] In the fitting I should be able to draw a curve without pressing enter and refitting
- [x] The Graph axis are wrong. They should change according to the Axes chose.
- [x] Fields should be called Axes
- [x] Default rows per table = 100
- [x] Values in the fitting should be picked in the plot (using mouse clicking)
- [x] tagging not working in TAS?
- [x] Fitting should be done only on clicking Fit (rename re-fit to fit?). button should be greyed out (?) while fitting. Increasing number of iterations you will see the fitting is much slower... See web workers!

- [x] Home (landing?) page with links for the several options.

- [x] Change iterations range. From 10 to 1000
- [x] When picking the coordinates from the plot all fields change to (X). Can we have that only for the field that we are picking the value? Also looks like when we are editing values all of them turn to (X):

![image](https://user-images.githubusercontent.com/1866557/35679448-0e9da700-0725-11e8-866a-e03c2f50d511.png)

- [x] If the parameter `fetch` is the the url, for example:
http://localhost:8080/#/TAS-Browse?fetch=/external/fetch/tas
Fetch the data automaticcly from that URL. No need to click fetch.

- [x] In the Browse data link arrow keys < and > with the next and previous file.
![image](https://user-images.githubusercontent.com/1866557/35738075-b6c7850a-07fb-11e8-9c61-7324eb08b4d3.png)

- [x] Revise store (state management) structure. Main groups SANS & TAS. Nest modules beneath: Browse, Stitch, Fit, etc.
